//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DW.Framework.SMS.SmsAPI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://18dx.cn/api/services", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://18dx.cn/api/services", ConfigurationName="SmsAPI.ServicesSoap")]
    public interface ServicesSoap {
        
        // CODEGEN: 命名空间 http://18dx.cn/api/services 的元素名称 user 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://18dx.cn/api/services/SendSms", ReplyAction="*")]
        DW.Framework.SMS.SmsAPI.SendSmsResponse SendSms(DW.Framework.SMS.SmsAPI.SendSmsRequest request);
        
        // CODEGEN: 命名空间 http://18dx.cn/api/services 的元素名称 source 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://18dx.cn/api/services/GetQueryStringValue", ReplyAction="*")]
        DW.Framework.SMS.SmsAPI.GetQueryStringValueResponse GetQueryStringValue(DW.Framework.SMS.SmsAPI.GetQueryStringValueRequest request);
        
        // CODEGEN: 命名空间 http://18dx.cn/api/services 的元素名称 source 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://18dx.cn/api/services/GetMD5String", ReplyAction="*")]
        DW.Framework.SMS.SmsAPI.GetMD5StringResponse GetMD5String(DW.Framework.SMS.SmsAPI.GetMD5StringRequest request);
        
        // CODEGEN: 命名空间 http://18dx.cn/api/services 的元素名称 user 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://18dx.cn/api/services/GetBalance", ReplyAction="*")]
        DW.Framework.SMS.SmsAPI.GetBalanceResponse GetBalance(DW.Framework.SMS.SmsAPI.GetBalanceRequest request);
        
        // CODEGEN: 命名空间 http://18dx.cn/api/services 的元素名称 cont 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://18dx.cn/api/services/GetContEncodingValue", ReplyAction="*")]
        DW.Framework.SMS.SmsAPI.GetContEncodingValueResponse GetContEncodingValue(DW.Framework.SMS.SmsAPI.GetContEncodingValueRequest request);
        
        // CODEGEN: 命名空间 http://18dx.cn/api/services 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://18dx.cn/api/services/HelloWorld", ReplyAction="*")]
        DW.Framework.SMS.SmsAPI.HelloWorldResponse HelloWorld(DW.Framework.SMS.SmsAPI.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(DW.Framework.SMS.SmsAPI.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long msgid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public DW.Framework.SMS.SmsAPI.ArrayOfString mobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public DW.Framework.SMS.SmsAPI.ArrayOfString conts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string plantime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string hashcode;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string user, long msgid, DW.Framework.SMS.SmsAPI.ArrayOfString mobiles, DW.Framework.SMS.SmsAPI.ArrayOfString conts, string plantime, string hashcode) {
            this.user = user;
            this.msgid = msgid;
            this.mobiles = mobiles;
            this.conts = conts;
            this.plantime = plantime;
            this.hashcode = hashcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(DW.Framework.SMS.SmsAPI.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringValue", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.GetQueryStringValueRequestBody Body;
        
        public GetQueryStringValueRequest() {
        }
        
        public GetQueryStringValueRequest(DW.Framework.SMS.SmsAPI.GetQueryStringValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class GetQueryStringValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public GetQueryStringValueRequestBody() {
        }
        
        public GetQueryStringValueRequestBody(string source, string name) {
            this.source = source;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringValueResponse", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.GetQueryStringValueResponseBody Body;
        
        public GetQueryStringValueResponse() {
        }
        
        public GetQueryStringValueResponse(DW.Framework.SMS.SmsAPI.GetQueryStringValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class GetQueryStringValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetQueryStringValueResult;
        
        public GetQueryStringValueResponseBody() {
        }
        
        public GetQueryStringValueResponseBody(string GetQueryStringValueResult) {
            this.GetQueryStringValueResult = GetQueryStringValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMD5StringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMD5String", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.GetMD5StringRequestBody Body;
        
        public GetMD5StringRequest() {
        }
        
        public GetMD5StringRequest(DW.Framework.SMS.SmsAPI.GetMD5StringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class GetMD5StringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        public GetMD5StringRequestBody() {
        }
        
        public GetMD5StringRequestBody(string source) {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMD5StringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMD5StringResponse", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.GetMD5StringResponseBody Body;
        
        public GetMD5StringResponse() {
        }
        
        public GetMD5StringResponse(DW.Framework.SMS.SmsAPI.GetMD5StringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class GetMD5StringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMD5StringResult;
        
        public GetMD5StringResponseBody() {
        }
        
        public GetMD5StringResponseBody(string GetMD5StringResult) {
            this.GetMD5StringResult = GetMD5StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(DW.Framework.SMS.SmsAPI.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashcode;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(string user, string hashcode) {
            this.user = user;
            this.hashcode = hashcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(DW.Framework.SMS.SmsAPI.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(int GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContEncodingValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContEncodingValue", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.GetContEncodingValueRequestBody Body;
        
        public GetContEncodingValueRequest() {
        }
        
        public GetContEncodingValueRequest(DW.Framework.SMS.SmsAPI.GetContEncodingValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class GetContEncodingValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cont;
        
        public GetContEncodingValueRequestBody() {
        }
        
        public GetContEncodingValueRequestBody(string cont) {
            this.cont = cont;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContEncodingValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContEncodingValueResponse", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.GetContEncodingValueResponseBody Body;
        
        public GetContEncodingValueResponse() {
        }
        
        public GetContEncodingValueResponse(DW.Framework.SMS.SmsAPI.GetContEncodingValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class GetContEncodingValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetContEncodingValueResult;
        
        public GetContEncodingValueResponseBody() {
        }
        
        public GetContEncodingValueResponseBody(string GetContEncodingValueResult) {
            this.GetContEncodingValueResult = GetContEncodingValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DW.Framework.SMS.SmsAPI.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://18dx.cn/api/services", Order=0)]
        public DW.Framework.SMS.SmsAPI.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DW.Framework.SMS.SmsAPI.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://18dx.cn/api/services")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesSoapChannel : DW.Framework.SMS.SmsAPI.ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesSoapClient : System.ServiceModel.ClientBase<DW.Framework.SMS.SmsAPI.ServicesSoap>, DW.Framework.SMS.SmsAPI.ServicesSoap {
        
        public ServicesSoapClient() {
        }
        
        public ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DW.Framework.SMS.SmsAPI.SendSmsResponse DW.Framework.SMS.SmsAPI.ServicesSoap.SendSms(DW.Framework.SMS.SmsAPI.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string user, long msgid, DW.Framework.SMS.SmsAPI.ArrayOfString mobiles, DW.Framework.SMS.SmsAPI.ArrayOfString conts, string plantime, string hashcode) {
            DW.Framework.SMS.SmsAPI.SendSmsRequest inValue = new DW.Framework.SMS.SmsAPI.SendSmsRequest();
            inValue.Body = new DW.Framework.SMS.SmsAPI.SendSmsRequestBody();
            inValue.Body.user = user;
            inValue.Body.msgid = msgid;
            inValue.Body.mobiles = mobiles;
            inValue.Body.conts = conts;
            inValue.Body.plantime = plantime;
            inValue.Body.hashcode = hashcode;
            DW.Framework.SMS.SmsAPI.SendSmsResponse retVal = ((DW.Framework.SMS.SmsAPI.ServicesSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DW.Framework.SMS.SmsAPI.GetQueryStringValueResponse DW.Framework.SMS.SmsAPI.ServicesSoap.GetQueryStringValue(DW.Framework.SMS.SmsAPI.GetQueryStringValueRequest request) {
            return base.Channel.GetQueryStringValue(request);
        }
        
        public string GetQueryStringValue(string source, string name) {
            DW.Framework.SMS.SmsAPI.GetQueryStringValueRequest inValue = new DW.Framework.SMS.SmsAPI.GetQueryStringValueRequest();
            inValue.Body = new DW.Framework.SMS.SmsAPI.GetQueryStringValueRequestBody();
            inValue.Body.source = source;
            inValue.Body.name = name;
            DW.Framework.SMS.SmsAPI.GetQueryStringValueResponse retVal = ((DW.Framework.SMS.SmsAPI.ServicesSoap)(this)).GetQueryStringValue(inValue);
            return retVal.Body.GetQueryStringValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DW.Framework.SMS.SmsAPI.GetMD5StringResponse DW.Framework.SMS.SmsAPI.ServicesSoap.GetMD5String(DW.Framework.SMS.SmsAPI.GetMD5StringRequest request) {
            return base.Channel.GetMD5String(request);
        }
        
        public string GetMD5String(string source) {
            DW.Framework.SMS.SmsAPI.GetMD5StringRequest inValue = new DW.Framework.SMS.SmsAPI.GetMD5StringRequest();
            inValue.Body = new DW.Framework.SMS.SmsAPI.GetMD5StringRequestBody();
            inValue.Body.source = source;
            DW.Framework.SMS.SmsAPI.GetMD5StringResponse retVal = ((DW.Framework.SMS.SmsAPI.ServicesSoap)(this)).GetMD5String(inValue);
            return retVal.Body.GetMD5StringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DW.Framework.SMS.SmsAPI.GetBalanceResponse DW.Framework.SMS.SmsAPI.ServicesSoap.GetBalance(DW.Framework.SMS.SmsAPI.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public int GetBalance(string user, string hashcode) {
            DW.Framework.SMS.SmsAPI.GetBalanceRequest inValue = new DW.Framework.SMS.SmsAPI.GetBalanceRequest();
            inValue.Body = new DW.Framework.SMS.SmsAPI.GetBalanceRequestBody();
            inValue.Body.user = user;
            inValue.Body.hashcode = hashcode;
            DW.Framework.SMS.SmsAPI.GetBalanceResponse retVal = ((DW.Framework.SMS.SmsAPI.ServicesSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DW.Framework.SMS.SmsAPI.GetContEncodingValueResponse DW.Framework.SMS.SmsAPI.ServicesSoap.GetContEncodingValue(DW.Framework.SMS.SmsAPI.GetContEncodingValueRequest request) {
            return base.Channel.GetContEncodingValue(request);
        }
        
        public string GetContEncodingValue(string cont) {
            DW.Framework.SMS.SmsAPI.GetContEncodingValueRequest inValue = new DW.Framework.SMS.SmsAPI.GetContEncodingValueRequest();
            inValue.Body = new DW.Framework.SMS.SmsAPI.GetContEncodingValueRequestBody();
            inValue.Body.cont = cont;
            DW.Framework.SMS.SmsAPI.GetContEncodingValueResponse retVal = ((DW.Framework.SMS.SmsAPI.ServicesSoap)(this)).GetContEncodingValue(inValue);
            return retVal.Body.GetContEncodingValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DW.Framework.SMS.SmsAPI.HelloWorldResponse DW.Framework.SMS.SmsAPI.ServicesSoap.HelloWorld(DW.Framework.SMS.SmsAPI.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DW.Framework.SMS.SmsAPI.HelloWorldRequest inValue = new DW.Framework.SMS.SmsAPI.HelloWorldRequest();
            inValue.Body = new DW.Framework.SMS.SmsAPI.HelloWorldRequestBody();
            DW.Framework.SMS.SmsAPI.HelloWorldResponse retVal = ((DW.Framework.SMS.SmsAPI.ServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
    }
}
